steps:
  # 1. 指向 server 文件夹进行构建
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:google-22'
      - '--path=server'

  # 2. 推送镜像 (保持不变)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # 3. 部署 (保持不变)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY